
### root
GET {{base}}/
Accept: application/json


### check_mem_all

GET {{base}}/check_mem_all/available?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### check_mem

GET {{base}}/check_mem/0?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}



### launch - cuda

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "ag2sf",
    "sub_dir": "test1",
    "image_url": "http://localhost:8000/20231101-173105.jpeg",
    "audio_url": "http://localhost:8000/棉田.ape"
  },
  "launch": {
    "device_index": 0
  }
}


### launch - cpu

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "ss",
    "sub_dir": "test1",
    "image_url": "http://localhost:8000/20231101-173105.jpeg",
    "audio_url": "http://localhost:8000/棉田.ape"
  },
  "launch": {
    "hf_hub_offline": true
  }
}

### launch - run_mode thread/process/sync

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "ss",
    "sub_dir": "thread",
    "max_gen_len": 15,
    "image_url": "http://localhost:8000/20231101-173105.jpeg",
    "audio_url": "http://localhost:8000/你的样子.mp3"
  },
  "launch": {
    "hf_hub_offline": true,
    "run_mode": "thread"
  }
}


### launch - tt

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "CCiuoQicxcC5OZbP",
    "sub_dir": "2024-01-16",
    "max_gen_len": 60,
    "image_url": "https://oss-dev.tishi.top/tasks/2324882932984990/mj/18qcskmjdcccs007_Eastern_face_middle-aged_man_with_vicissitudes_77507a7b-2098-4762-b8c2-0072dc730a8c.png?image_process=crop,w_816,h_1456,x_816,y_0",
    "audio_url": "https://oss-prod.tishi.top/sds/dreamtalk/2024-01-14/vc3ABGKTHo5XGhG4/1705222946/output.mp4",
    "cfg_scale": 2,
    "img_crop": true
  },
  "launch": {
    "hf_hub_offline": true,
    "run_mode": "thread"
  }
}



### launch - tt

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "eeiuoQicxcC5OZbP",
    "sub_dir": "2024-01-16",
    "max_gen_len": 60,
    "image_url": "https://oss-dev.tishi.top/tasks/2324882932984990/mj/18qcskmjdcccs007_Eastern_face_middle-aged_man_with_vicissitudes_77507a7b-2098-4762-b8c2-0072dc730a8c.png?image_process=crop,w_816,h_1456,x_816,y_0",
    "audio_url": "https://oss-prod.tishi.top/sds/dreamtalk/vc3ABGKTHo5XGhG4/in/1705221508/1705221508.mp3",
    "cfg_scale": 2,
    "img_crop": true
  },
  "launch": {
    "hf_hub_offline": true,
    "run_mode": "thread"
  }
}

### task - status

POST {{base}}/task/ss/status
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "root_pid": "9417199",
  "sub_dir": "test1"
}


### result info

GET {{base}}/task/ss/test1/result
Accept: application/json
Authorization: {{auth}}


### cropped_image

GET {{base}}/task/ss/test1/result_file/20231101-173105-cropped.jpeg
Authorization: {{auth}}


### result_video

GET {{base}}/task/ss/test1/result_file/output.mp4
Authorization: {{auth}}


### detect face

POST {{base}}/detect_face
Content-Type: application/json
Authorization: {{auth}}

{
  "image_url": "http://localhost:8000/1700919408_1.png"
}


### crop face

POST {{base}}/crop_face
Content-Type: application/json
Authorization: {{auth}}

{
  "image_url": "http://localhost:8000/20231101-173105.jpeg"
}


### crop face 2

POST {{base}}/crop_face2
Content-Type: application/json
Authorization: {{auth}}

{
  "image_url": "http://localhost:8000/20231101-173105.jpeg"
}

