# general settings
# CUDA_VISIBLE_DEVICES=5 python basicsr/train.py -opt options/train/BasicVSR/0928_train_BasicVSR_hdtf3.yml --debug
name: 0928_train_BasicVSR_hdtf3
model_type: VideoRecurrentModel
scale: 2
num_gpu: auto  # official: 8 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: HDTF
    type: HDTFRecurrentDataset
    dataroot_gt: datasets/data/HDTF_images_100/512
    dataroot_lq: datasets/data/HDTF_images_100/256
    test_mode: False
    io_backend:
      type: disk

    num_frame: 7
    gt_size: 512
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: datasets/data/HDTF_images_100/512
    dataroot_lq: datasets/data/HDTF_images_100/256
    cache_data: True
    io_backend:
      type: disk
    num_frame: -1  # not needed

# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 30
  spynet_path: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth
  scale: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
